### ISSUE TITLE
Test Model Grid - Test photometry failing 

### ISSUE THREAD

**Issue by SherelynA** [BDNYC/sedkit#107]
`FAILED sedkit/tests/test_modelgrid.py::TestModelGrid::test_photometry - ValueError: cannot set a row with mismatched columns
`
This error seems to be related to the lack of a "weight" column in the model grid class data frame. @kelle and I haven't been able to fix this. 
@hover2pi , any thoughts or insight on this issue?

**Comment by SherelynA** [comment]
Here is some of the traceback 
`sedkit/modelgrid.py:623: in photometry
    phot.add_model(dataT if err else dataT[:2], weights=weights, label=row['label'], **params)
sedkit/modelgrid.py:229: in add_model
    self.index.loc[len(self.index)] = new_rec
../../opt/anaconda3/envs/sedkit-3.11/lib/python3.11/site-packages/pandas/core/indexing.py:911: in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
../../opt/anaconda3/envs/sedkit-3.11/lib/python3.11/site-packages/pandas/core/indexing.py:1932: in _setitem_with_indexer
    self._setitem_with_indexer_missing(indexer, value)
`

**Comment by kelle** [comment]
Fixed in #111
