### ISSUE TITLE
Fix tests on CI

### ISSUE THREAD

**Issue by kelle** [BDNYC/sedkit#110]
I thought I had got the tests running on GitHub Actions but now they aren't working.  Something is probably wrong in the .toml file.  :/

**Comment by kelle** [comment]
It looks like I got tests running in #99 but they broke again in #101

**Comment by hover2pi** [comment]
The .toml file was missing the `importlib_resources` dep. I have a PR I'm working on now where I included it as well as fixes for the test failures.

**Comment by kelle** [comment]
Oh right, I did know that. Thanks for working on this!

**Comment by kelle** [comment]
Closed by #111
