### ISSUE TITLE
Healpy Problem in Windows while Setting Up Sedkit

### ISSUE THREAD

**Issue by SherelynA** [BDNYC/sedkit#118]
It appears that when trying to install sedkit on a windows machine, there is a problem with downloading Healpy, which stops the package from being downloaded. @hover2pi have you experienced this problem and do you know of any solutions?

**Comment by kelle** [comment]
New issue #121 for making healpy and dustmaps optional dependencies.

@SherelynA , have you resolved this issue? how urgently do you need to get sedkit installed on a windows machine?

**Comment by SherelynA** [comment]
@kelle, with the updated pip install sedkit working now, this shouldn't be a problem anymore. For some reason, when trying to install sedkit using conda in a windows machine, healpy and dustmaps were a problem. However, with the pip install option it should work now.

**Comment by kelle** [comment]
Ok. Can always reopen if needed.
