### ISSUE TITLE
Outdated pip install sedkit

### ISSUE THREAD

**Issue by SherelynA** [BDNYC/sedkit#119]
@hover2pi currently the pip install sedkit installs the v.1.2.4. We need to update it so it installs the latest version.

**Comment by kelle** [comment]
Yes, we need to figure out the workflow for uploading new versions to Pypi. I will look into this now.

**Comment by kelle** [comment]
Being addressed in #122

**Comment by kelle** [comment]
Hm, not working: 
```
Checking dist/sedkit-0.0.0-py3-none-any.whl: FAILED
ERROR    `long_description` has syntax errors in markup and would not be        
         rendered on PyPI.                                                      
         No content rendered from RST source.                                   
WARNING  `long_description_content_type` missing. defaulting to `text/x-rst`.   
Checking dist/sedkit-0.0.0.tar.gz: PASSED with warnings
WARNING  `long_description_content_type` missing. defaulting to `text/x-rst`.   
WARNING  `long_description` missing.

**Comment by kelle** [comment]
fix ref: https://github.com/pypa/gh-action-pypi-publish/issues/162#issuecomment-1813356002

**Comment by kelle** [comment]
ok, removed BTSETTL models in #126 to reduce package size and the release workflow now works!  Please try to `pip install sedkit` and see if it works.  You should be getting 2.0.3.

**Comment by hover2pi** [comment]
Closing this.
