### ISSUE TITLE
Axes of the Bokeh Plots are off

### ISSUE THREAD

**Issue by SherelynA** [BDNYC/sedkit#136]
When I plot the sed, for some reason it shows me a blanks space far way from where the actual sed is. It seems like the axes are not being set correctly or something of that sort. 

<img width="913" alt="Screenshot 2024-11-14 at 11 30 07 PM" src="https://github.com/user-attachments/assets/9158fd47-0a39-4656-8c27-731d3937d7bb">

And then when I do find it after moving in the bokeh plot it seems like it is upside down. 
<img width="913" alt="Screenshot 2024-11-14 at 11 33 05 PM" src="https://github.com/user-attachments/assets/4b871e18-0974-4e50-aacb-ecb883c21b16">

**Comment by SherelynA** [comment]
@kelle thoughts?

**Comment by kelle** [comment]
Seeing the figures is not enough information to debug. Please also include other diagnostic information about the SED object. One thing in particular to look at is the wavelength array.

**Comment by SherelynA** [comment]
I no longer get this problem, not sure what fixed it but the current version doesn't have this problem that I was getting.
